all:
  children:
    k3s_server:
      hosts:
        carbomba:
          ansible_host: 192.168.11.12
          ansible_user: filip
          ansible_ssh_private_key_file: ~/.ssh/carbomba
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3.13
