all:
  children:
    pc:
      hosts:
        arch-live:
          ansible_user: root
          ansible_host: 192.168.11.102
          ansible_python_interpreter: /usr/bin/python
          ansible_become: true
        steam-machine:
          ansible_user: filip
          ansible_host: 192.168.11.243
          ansible_python_interpreter: /usr/bin/python
          ansible_become: true
    k3s_server:
      hosts:
        carbomba:
          ansible_host: c
          ansible_user: filip
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3.13
    cloud:
      hosts:
        vps:
          ansible_host: vps
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3.13
