all:
  children:
    k3s_server:
      hosts:
        carbomba:
          ansible_host: c
          ansible_user: filip
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3.13
    cloud:
      hosts:
        vps:
          ansible_host: vps
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3.13
