cert_manager:
  version: v1.19.1
  namespace: cert-manager

acme:
  email: filipnajman@protonmail.me
  cluster_issuer_name: letsencrypt-cloudflare

cloudflare:
  # api_token: "YOUR_ENCRYPTED_TOKEN_HERE"
  secret_name: cloudflare-api-token-secret
  secret_key: api-token
  
certificate:
  name: wildcard-cert
  namespace: default
  secret_name: wildcard-cert-tls
  wildcard_domains:
    - "*.d.32123.pl"
    - "d.32123.pl"