- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Apply deployment
  kubernetes.core.k8s:
    state: present
    template: "deployment.j2"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Apply service
  kubernetes.core.k8s:
    state: present
    template: "service.j2"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Apply ingress
  kubernetes.core.k8s:
    state: present
    template: "ingress.j2"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
